Feature/cest tests migration
dmstr/phd5-app pull request #24
Opened 2019-09-27 08:00 UTC by amk0

2019-09-30 10:32 UTC, schmunk42 commented
Tests did not fully pass

```
PHP Fatal error:  Cannot declare class HomeCest, because the name is already in use in /app/tests/codeception/functional/HomeCest.php on line 4
```

https://travis-ci.org/dmstr/phd5-app/builds/590302498#L2963

2019-09-30 16:12 UTC, schmunk42 commented
The new tests do not have a `@group mandatory` annotation, I think it would be good to keep it.

CC: @eluhr @handcode

2019-10-01 08:13 UTC, amk0 commented
added the test groups back to all tests

2019-10-01 08:37 UTC, schmunk42 requested changes

2019-10-01 08:37 UTC, schmunk42 commented on tests/codeception/e2e/app/LoginCest.php
> +    public function tryToTest(E2eTester $I)
all tests are named `tryToTest`, could you give them a more meaningful name, here eg. `frontendLogin`, usually the string in `wantTo` is  good guide.

2019-10-02 07:32 UTC, merged

2019-10-02 07:32 UTC, schmunk42 commented
Thank you!